name: Build

on:
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install PureScript and Spago
      run: npm install -g purescript spago
    - name: Install dependencies
      run: |
        npm install
        spago install
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
